---
language: python
services:
  - docker
python:
  - "3.7"
env:
  matrix:
    - UBUNTU_IMAGE_TAG: focal
    - UBUNTU_IMAGE_TAG: bionic
    - UBUNTU_IMAGE_TAG: xenial
install:
  - pip install testinfra molecule docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
