---
- name: Create UniFi volumes
  docker_volume:
    name: "{{ item }}"
  loop:
    - unifi_data
    - unifi_log
    - unifi_cert
    - unifi_init.d
    
- name: Create UniFi network
  docker_network:
    name: "{{ unifi_docker_network }}"

- name: Create UniFi container
  docker_container:
    name: "{{ unifi_docker_container_name }}"
    image: "jacobalberty/unifi:{{ unifi_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    init: true
    published_ports:
      - '3478:3478/udp'
      - '8080:8080'
      - '8443:8443'
      - '8880:8880'
      - '6789:6789'
      - '10001:10001/udp'
    networks:
      - name: "{{ unifi_docker_network }}"
    volumes:
      - "unifi_data:/unifi/data"
      - "unifi_log:/unifi/log"
      - "unifi_cert:/unifi/cert"
      - "unifi_init.d:/unifi/init.d"
    env:
      TZ: "{{ unifi_docker_tz }}"
