---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
